name: Build APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g eas-cli
      - run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ 3fz9ugHQI3mXvWzo12C7Xf7m9IEeu56PoPxWj6Zz }}
